### PR TITLE
Should concat the path info if the request path override comes in the defaults

### PR DESCRIPTION
**Pull request by mrkaspa**
I wan to redirect to a diferent generated request path but always ends concatenating the old path and is confusing because when I init the plug I set the url, may be my use case is different because I have to call this in a dynamic way inside a controller this way

```elixir

  def all(conn, _params) do
    path = String.split(conn.request_path, "/v1/files/") |> Enum.join("/")
    url = get_url() <> path <> "?" <> conn.query_string
    opts = ReverseProxyPlug.init(upstream: url, response_mode: :buffer)
    ReverseProxyPlug.call(conn, opts)
  end

```

What would be the best way to handle this in the library, I supossed that if I was passing by the value in the upstream it should take that one. I'm open to any comments, thanks

### CODE REVIEW

**Comment by mrkaspa** [comment]
I think I have to check the tests first

**Comment by mrkaspa** [comment]
I decided to add another param to init the plug just in case I want this behaviour, wdyt?

**Comment by msz** [comment]
It seems that what you want to do is to discard the original path of the request. You can modify the original request in any way you like before passing it to ReverseProxyPlug. So how about this?

```elixir
defmodule MyReverseProxyPlug do
  use Plug.Builder

  plug(:reset_path_info)
  plug(ReverseProxyPlug, upstream: UpstreamUrl.get(), response_mode: :buffer)

  defp reset_path_info(conn, _opts) do
    %{conn | path_info: []}
  end
end

```

**Comment by mrkaspa** [comment]
Great seems to work

**Pull request closed without merging**
