### PR TITLE
`host` header now includes the port when is not the default for the scheme

### PR DESCRIPTION
**Pull request by GermanDZ**
Following the recommendation in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host and resolving the issue #26.

### CODE REVIEW

**Comment by msz** [comment]
Circle CI builds for forks were not turned on so tested manually this time.

**Comment by GermanDZ** [comment]
I don't know what's happening with CircleCI, but since is not passing the tests, I cannot merge.

Tests are passing in my workstation (famous last words).

**Comment by bamorim** [comment]
Any plans to release this fix to hex.pm?

**Comment by msz** [comment]
Now released in v1.1.1.

**Pull request merged**
